import {
  MAX_TIER,
  NO_SIGNALS,
  TIER_NAMES,
  cardPoints,
  renderContributorCardSvg,
  type ContributorSignals,
} from "@/lib/contributor-card"

/**
 * Preview surface for the experimental contributor card.
 *
 * Unlisted on purpose — nothing links here, and nothing in the product imports
 * the generator yet. The question this page exists to answer is whether the
 * ladder actually looks like progress when you see all six steps at once, and
 * whether two different people at the same tier still look like different
 * people. Both are things you have to look at; neither survives being argued
 * about in a pull request.
 *
 * Delete this route along with `lib/contributor-card.ts` if the answer is no.
 */

export const dynamic = "force-static"

/**
 * One example per tier, written as the signals a real person would have rather
 * than as points. If a row's numbers look implausible for its tier, that is the
 * weighting being wrong, and it should be visible here rather than discovered
 * after launch.
 */
const LADDER: ContributorSignals[] = [
  NO_SIGNALS,
  { confirmedFalsePositives: 0, cleanStreakWeeks: 3, areasTouched: 0 },
  { confirmedFalsePositives: 1, cleanStreakWeeks: 2, areasTouched: 2 },
  { confirmedFalsePositives: 1, cleanStreakWeeks: 6, areasTouched: 4 },
  { confirmedFalsePositives: 2, cleanStreakWeeks: 9, areasTouched: 5 },
  { confirmedFalsePositives: 4, cleanStreakWeeks: 12, areasTouched: 6 },
]

/** Same signals, different logins — the check that the seed still does its job. */
const SEEDS = ["octocat", "YpCIIIaK", "torvalds", "gaearon", "sindresorhus"]

function Card({ svg }: { svg: string }) {
  return (
    <div
      className="[&>svg]:h-auto [&>svg]:w-full"
      // Generated by our own pure function from validated inputs; there is no
      // user-supplied markup in it, and every text value goes through esc().
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  )
}

export default function CardLabPage() {
  return (
    <main className="mx-auto max-w-6xl px-6 py-12">
      <h1 className="text-2xl font-bold">Contributor card — lab</h1>
      <p className="text-muted-foreground mt-2 max-w-2xl text-sm">
        Experimental. The login seeds the look; the signals decide how much
        structure is drawn on top. Nothing here is wired to real data.
      </p>

      <h2 className="mt-10 text-lg font-semibold">The ladder</h2>
      <p className="text-muted-foreground mt-1 text-sm">
        One person, six tiers. It should read as the same card getting denser.
      </p>
      <div className="mt-5 grid grid-cols-2 gap-5 sm:grid-cols-3 lg:grid-cols-6">
        {LADDER.map((signals, tier) => (
          <figure key={tier} className="space-y-2">
            <Card svg={renderContributorCardSvg("octocat", signals)} />
            <figcaption className="text-muted-foreground text-xs">
              {TIER_NAMES[Math.min(tier, MAX_TIER)]} · {cardPoints(signals)} pts
            </figcaption>
          </figure>
        ))}
      </div>

      <h2 className="mt-12 text-lg font-semibold">Same tier, different people</h2>
      <p className="text-muted-foreground mt-1 text-sm">
        Identical signals. If these look interchangeable, the seed is not
        carrying enough.
      </p>
      <div className="mt-5 grid grid-cols-2 gap-5 sm:grid-cols-3 lg:grid-cols-5">
        {SEEDS.map((login) => (
          <figure key={login} className="space-y-2">
            <Card svg={renderContributorCardSvg(login, LADDER[3])} />
            <figcaption className="text-muted-foreground text-xs">{login}</figcaption>
          </figure>
        ))}
      </div>

      <h2 className="mt-12 text-lg font-semibold">Light theme</h2>
      <div className="mt-5 grid grid-cols-2 gap-5 sm:grid-cols-3 lg:grid-cols-6">
        {LADDER.map((signals, tier) => (
          <figure key={tier} className="space-y-2">
            <Card svg={renderContributorCardSvg("octocat", signals, { theme: "light" })} />
            <figcaption className="text-muted-foreground text-xs">tier {tier}</figcaption>
          </figure>
        ))}
      </div>
    </main>
  )
}
