import {
  MAX_TIER,
  NO_SIGNALS,
  TIER_NAMES,
  cardPoints,
  renderContributorCardSvg,
  type ContributorSignals,
} from "@/lib/contributor-card"
import { renderPersonCardSvg, type PersonFacts } from "@/lib/person-card"

/**
 * Preview surface for the experimental contributor card.
 *
 * Unlisted on purpose — nothing links here, and nothing in the product imports
 * the generator yet. The question this page exists to answer is whether the
 * ladder actually looks like progress when you see all six steps at once, and
 * whether two different people at the same tier still look like different
 * people. Both are things you have to look at; neither survives being argued
 * about in a pull request.
 *
 * Delete this route along with `lib/contributor-card.ts` if the answer is no.
 */

export const dynamic = "force-static"

/**
 * One example per tier, written as the signals a real person would have rather
 * than as points. If a row's numbers look implausible for its tier, that is the
 * weighting being wrong, and it should be visible here rather than discovered
 * after launch.
 */
const LADDER: ContributorSignals[] = [
  NO_SIGNALS,
  { confirmedFalsePositives: 0, cleanStreakWeeks: 3, areasTouched: 0 },
  { confirmedFalsePositives: 1, cleanStreakWeeks: 2, areasTouched: 2 },
  { confirmedFalsePositives: 1, cleanStreakWeeks: 6, areasTouched: 4 },
  { confirmedFalsePositives: 2, cleanStreakWeeks: 9, areasTouched: 5 },
  { confirmedFalsePositives: 4, cleanStreakWeeks: 12, areasTouched: 6 },
]

/** Same signals, different logins — the check that the seed still does its job. */
const SEEDS = ["octocat", "YpCIIIaK", "torvalds", "gaearon", "sindresorhus"]

/**
 * The person card, which needs no contribution history at all.
 *
 * Ordered from a bare handle to a filled-in profile, because the thing worth
 * checking is that the sparse one still looks deliberate rather than broken.
 */
const PEOPLE: PersonFacts[] = [
  { login: "octocat" },
  { login: "YpCIIIaK", name: "Vova", location: "Cyprus" },
  {
    login: "torvalds",
    name: "Linus Torvalds",
    bio: "Just a guy who writes kernels and reads mail.",
    location: "Portland, OR",
    joinedYear: 2011,
    publicRepos: 7,
    followers: 231000,
  },
  {
    login: "gaearon",
    name: "dan",
    bio: "wrote some code, made some tools, mostly just replying to issues",
    company: "@bsky",
    location: "London, UK",
    joinedYear: 2011,
    publicRepos: 260,
    followers: 82400,
  },
  {
    login: "sindresorhus",
    name: "Sindre Sorhus",
    bio: "Full-time open sourcerer. Maker of things.",
    company: "Open source",
    location: "Norway",
    joinedYear: 2009,
    publicRepos: 1100,
    followers: 62000,
  },
]

function Card({ svg }: { svg: string }) {
  return (
    <div
      className="[&>svg]:h-auto [&>svg]:w-full"
      // Generated by our own pure function from validated inputs; there is no
      // user-supplied markup in it, and every text value goes through esc().
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  )
}

export default function CardLabPage() {
  return (
    <main className="mx-auto max-w-6xl px-6 py-12">
      <h1 className="text-2xl font-bold">Contributor card — lab</h1>
      <p className="text-muted-foreground mt-2 max-w-2xl text-sm">
        Experimental. The login seeds the look; the signals decide how much
        structure is drawn on top. Nothing here is wired to real data.
      </p>

      <h2 className="mt-10 text-lg font-semibold">The person card</h2>
      <p className="text-muted-foreground mt-1 text-sm">
        No tiers and no contribution history — just who somebody is. The handle
        seeds the look; the facts fill it in. A bare handle should still look
        deliberate.
      </p>
      <div className="mt-5 grid grid-cols-2 gap-5 sm:grid-cols-3 lg:grid-cols-5">
        {PEOPLE.map((person) => (
          <figure key={person.login} className="space-y-2">
            <Card svg={renderPersonCardSvg(person)} />
            <figcaption className="text-muted-foreground text-xs">
              {Object.keys(person).length - 1} facts known
            </figcaption>
          </figure>
        ))}
      </div>

      <h2 className="mt-12 text-lg font-semibold">The wide layout</h2>
      <p className="text-muted-foreground mt-1 text-sm">
        Same card, README proportions — <code>?size=wide</code>. The lattice
        moves up when somebody has no bio, so a quiet profile does not render as
        a band of empty card.
      </p>
      <div className="mt-5 grid gap-5 sm:grid-cols-2">
        {PEOPLE.slice(1).map((person) => (
          <Card key={person.login} svg={renderPersonCardSvg(person, { layout: "wide" })} />
        ))}
      </div>

      <h2 className="mt-12 text-lg font-semibold">Same person, both cards</h2>
      <p className="text-muted-foreground mt-1 text-sm">
        They should read as one identity seen twice, not as two products.
      </p>
      <div className="mt-5 grid grid-cols-2 gap-5 sm:grid-cols-4">
        <Card svg={renderPersonCardSvg(PEOPLE[3])} />
        <Card svg={renderContributorCardSvg("gaearon", LADDER[3])} />
        <Card svg={renderPersonCardSvg(PEOPLE[4])} />
        <Card svg={renderContributorCardSvg("sindresorhus", LADDER[3])} />
      </div>

      <h2 className="mt-12 text-lg font-semibold">The ladder</h2>
      <p className="text-muted-foreground mt-1 text-sm">
        One person, six tiers. It should read as the same card getting denser.
      </p>
      <div className="mt-5 grid grid-cols-2 gap-5 sm:grid-cols-3 lg:grid-cols-6">
        {LADDER.map((signals, tier) => (
          <figure key={tier} className="space-y-2">
            <Card svg={renderContributorCardSvg("octocat", signals)} />
            <figcaption className="text-muted-foreground text-xs">
              {TIER_NAMES[Math.min(tier, MAX_TIER)]} · {cardPoints(signals)} pts
            </figcaption>
          </figure>
        ))}
      </div>

      <h2 className="mt-12 text-lg font-semibold">Same tier, different people</h2>
      <p className="text-muted-foreground mt-1 text-sm">
        Identical signals. If these look interchangeable, the seed is not
        carrying enough.
      </p>
      <div className="mt-5 grid grid-cols-2 gap-5 sm:grid-cols-3 lg:grid-cols-5">
        {SEEDS.map((login) => (
          <figure key={login} className="space-y-2">
            <Card svg={renderContributorCardSvg(login, LADDER[3])} />
            <figcaption className="text-muted-foreground text-xs">{login}</figcaption>
          </figure>
        ))}
      </div>

      <h2 className="mt-12 text-lg font-semibold">Light theme</h2>
      <div className="mt-5 grid grid-cols-2 gap-5 sm:grid-cols-3 lg:grid-cols-6">
        {LADDER.map((signals, tier) => (
          <figure key={tier} className="space-y-2">
            <Card svg={renderContributorCardSvg("octocat", signals, { theme: "light" })} />
            <figcaption className="text-muted-foreground text-xs">tier {tier}</figcaption>
          </figure>
        ))}
      </div>
    </main>
  )
}
