/** Практики веб-аудита: вопросы охотника, не сценарии атаки. */

export type Practice = {
  id: string;
  owasp: string;
  title: string;
  titleEn: string;
  ask: string;
  askEn: string;
  look: string;
  lookEn: string;
};

export const PRACTICES: Practice[] = [
  {
    id: "broken-access",
    owasp: "A01",
    title: "Сломанный контроль доступа",
    titleEn: "Broken access control",
    ask: "Меняется ли ответ, если в запросе подставить свой идентификатор объекта вместо чужого — без перебора и без обхода авторизации?",
    askEn: "Does the response change if you use your own object id instead of another user’s — without brute force or auth bypass?",
    look: "Списки, UUID в URL, «мой» vs «чужой» id из своей учётки. Не чужие сессии.",
    lookEn: "Lists, UUIDs in URLs, your id vs another id from your own account. Never other people’s sessions.",
  },
  {
    id: "crypto",
    owasp: "A02",
    title: "Криптография",
    titleEn: "Cryptographic failures",
    ask: "Уходит ли секрет в URL, в HTML, в JWT без подписи, в cookie без Secure?",
    askEn: "Does a secret leak into a URL, HTML, an unsigned JWT, or a cookie without Secure?",
    look: "Токены в query, localStorage, ответы API. Не расшифровывать чужие данные.",
    lookEn: "Tokens in query, localStorage, API bodies. Do not decrypt other people’s data.",
  },
  {
    id: "injection",
    owasp: "A03",
    title: "Инъекции",
    titleEn: "Injection",
    ask: "Где вход пользователя попадает в SQL, команду, шаблон или HTML без кодирования?",
    askEn: "Where does user input reach SQL, a command, a template, or HTML without encoding?",
    look: "Стоки в коде и отражение в ответе. Не слать полезные нагрузки на прод.",
    lookEn: "Sinks in code and reflection in the response. Do not send payloads to production.",
  },
  {
    id: "design",
    owasp: "A04",
    title: "Небезопасный дизайн",
    titleEn: "Insecure design",
    ask: "Есть ли шаг, который система считает невозможным (повтор купона, минус в количестве, смена цены)?",
    askEn: "Is there a step the system treats as impossible (coupon reuse, negative qty, price change)?",
    look: "Бизнес-правила и идемпотентность. Проверять на своей песочнице программы.",
    lookEn: "Business rules and idempotency. Verify in the program’s own sandbox.",
  },
  {
    id: "misconfig",
    owasp: "A05",
    title: "Неверная конфигурация",
    titleEn: "Security misconfiguration",
    ask: "Какие заголовки, CORS, директории и панели открыты без нужды?",
    askEn: "Which headers, CORS, directories, and panels are exposed without need?",
    look: "HSTS, CSP, ACAO, server, debug. Один GET на известный путь, без словаря.",
    lookEn: "HSTS, CSP, ACAO, server, debug. One GET to a known path, no wordlists.",
  },
  {
    id: "components",
    owasp: "A06",
    title: "Уязвимые компоненты",
    titleEn: "Vulnerable components",
    ask: "Какие библиотеки в JS/ответе и есть ли известные CVE с исправлением?",
    askEn: "Which libraries appear in JS/response, and are there known CVEs with a fix?",
    look: "generator, package versions, CDN. Сообщать, не эксплуатировать CVE вживую.",
    lookEn: "generator, package versions, CDN. Report; do not exploit CVEs live.",
  },
  {
    id: "auth",
    owasp: "A07",
    title: "Аутентификация",
    titleEn: "Identification and authentication",
    ask: "Сброс пароля, MFA, сессия после logout, cookie SameSite — что ломается на своём аккаунте?",
    askEn: "Password reset, MFA, session after logout, SameSite — what breaks on your own account?",
    look: "Свои два ящика. Не чужие OTP и не перебор паролей.",
    lookEn: "Your two mailboxes. No one else’s OTP and no password spraying.",
  },
  {
    id: "integrity",
    owasp: "A08",
    title: "Целостность ПО",
    titleEn: "Software and data integrity",
    ask: "Подписывается ли обновление, вебхук, CI-артефакт? Можно ли подменить URL своего пайплайна в скоупе?",
    askEn: "Are updates, webhooks, CI artifacts signed? Can you swap a URL in your in-scope pipeline?",
    look: "SRI, webhook secrets, supply chain. Не трогать чужой прод.",
    lookEn: "SRI, webhook secrets, supply chain. Do not touch someone else’s prod.",
  },
  {
    id: "logging",
    owasp: "A09",
    title: "Логи и мониторинг",
    titleEn: "Logging and monitoring",
    ask: "Попадают ли секреты в логи, которые программа отдаёт в скоупе (debug, /metrics, трейсы)?",
    askEn: "Do secrets land in logs the program exposes in scope (debug, /metrics, traces)?",
    look: "Только опубликованные эндпоинты скоупа.",
    lookEn: "Only published in-scope endpoints.",
  },
  {
    id: "ssrf",
    owasp: "A10",
    title: "SSRF",
    titleEn: "SSRF",
    ask: "Есть ли поле «URL для импорта», которое ходит наружу? Проверять на локальном стенде программы.",
    askEn: "Is there an “import URL” field that the server fetches? Verify on the program’s local staging.",
    look: "Не целиться в метаданные облака и не сканировать чужие сети.",
    lookEn: "Do not aim at cloud metadata and do not scan other people’s networks.",
  },
  {
    id: "csrf",
    owasp: "CSRF",
    title: "CSRF",
    titleEn: "CSRF",
    ask: "Меняет ли состояние POST без токена / без SameSite, если запрос с другого origin?",
    askEn: "Does a POST change state without a token / SameSite if it comes from another origin?",
    look: "Своя сессия, своя песочница. Не слать чужим пользователям.",
    lookEn: "Your session, your sandbox. Do not send this to other users.",
  },
  {
    id: "xss",
    owasp: "XSS",
    title: "XSS",
    titleEn: "XSS",
    ask: "Где вывод в DOM/HTML без экранирования? Достаточно своего отражения безопасной строки.",
    askEn: "Where does output hit DOM/HTML without encoding? Your own reflection of a safe marker is enough.",
    look: "Маркер вроде auditscout-test. Не cookie-stealer и не черви.",
    lookEn: "A marker like auditscout-test. No cookie stealers and no worms.",
  },
  {
    id: "upload",
    owasp: "UPLOAD",
    title: "Загрузка файлов",
    titleEn: "File upload",
    ask: "Какой тип, размер, путь и исполнение принимает загрузка на стенде?",
    askEn: "What type, size, path, and execution does upload accept on staging?",
    look: "Свой безобидный файл. Не webshell на прод.",
    lookEn: "Your own harmless file. No webshells on production.",
  },
  {
    id: "cache",
    owasp: "CACHE",
    title: "Отравление кэша / хоста",
    titleEn: "Cache / host poisoning",
    ask: "Влияет ли Host / X-Forwarded-* на ссылки в ответе так, что это увидят другие?",
    askEn: "Do Host / X-Forwarded-* change links in the response in a way others would see?",
    look: "Не отравлённый кэш для всех пользователей. Только наблюдение своего ответа.",
    lookEn: "Do not poison the cache for everyone. Observe only your own response.",
  },
  {
    id: "disclose",
    owasp: "POLICY",
    title: "Как не навредить",
    titleEn: "Do no harm",
    ask: "Находка уходит только в портал программы. Прод не ломаем, данные чужих аккаунтов не читаем, эксплойт не публикуем.",
    askEn: "A finding goes only to the program portal. Do not break prod, do not read others’ data, do not publish an exploit.",
    look: "security.txt, политику скоупа, PII stop.",
    lookEn: "security.txt, scope policy, PII stop.",
  },
];
